apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bey6zgk0g-nodejs 
  janus-idp.io/tekton: bey6zgk0g-nodejs
  backstage.io/kubernetes-id: bey6zgk0g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bey6zgk0g-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  